server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zhangxin
    url: jdbc:mysql://175.178.8.252:4306/zhangxin?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
  freemarker:
    settings:
      classic_compatible: true #处理空值
      datetime_format: yyy-MM-dd HH:mm
      number_format: 0.##
servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 100MB
mybatis-plus:
  type-aliases-package: com.melo.gold.entity
  mapper-locations: mapper/*.xml

